# Generated by Django 5.1.1 on 2025-12-20 07:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('partner', 'Partner'), ('team_member', 'Team Member')], default='team_member', help_text='User role for access control', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deal_size', models.DecimalField(decimal_places=2, help_text='Total deal size in INR', max_digits=15)),
                ('ticket_size', models.DecimalField(decimal_places=2, help_text='Minimum ticket size in INR', max_digits=15)),
                ('round_no', models.PositiveIntegerField(default=1, verbose_name='Round Number')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('closing', 'Closing'), ('closed', 'Closed')], default='new', max_length=20)),
                ('approval_workflow_status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Approval Workflow Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('document_type', models.CharField(choices=[('kyc', 'KYC Document'), ('bank', 'Bank Statement'), ('deal_doc', 'Deal Document'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('pan', models.CharField(help_text='PAN Card Number', max_length=10, unique=True)),
                ('aadhaar', models.CharField(help_text='Aadhaar Number (will be masked in display)', max_length=12, unique=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('group', models.CharField(choices=[('A', 'Group A (>1Cr)'), ('B', 'Group B (≤1Cr)')], default='B', help_text='Group A for investments >1Cr, Group B for ≤1Cr', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team_member', models.ForeignKey(blank=True, help_text='Team member assigned to manage this investor', limit_choices_to={'role': 'team_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_investors', to=settings.AUTH_USER_MODEL)),
                ('family_head', models.ForeignKey(blank=True, help_text='Family head for family grouping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Committed/Interested amount in INR', max_digits=15)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('committed', 'Committed'), ('paid', 'Paid')], default='interested', max_length=20)),
                ('payment_proof', models.FileField(blank=True, help_text='Upload payment proof document', null=True, upload_to='payment_proofs/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='investors.deal')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Commitment',
                'verbose_name_plural': 'Commitments',
                'ordering': ['-created_at'],
                'unique_together': {('investor', 'deal')},
            },
        ),
    ]
