# Generated by Django 5.1.1 on 2025-12-20 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='approval_workflow_status',
        ),
        migrations.AddField(
            model_name='deal',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved')], default='draft', help_text='Deal workflow status: Draft -> Review -> Approved', max_length=20, verbose_name='Workflow Status'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investment_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Investment capacity in INR (used to automatically assign Group A/B)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='group',
            field=models.CharField(choices=[('A', 'Group A (>1Cr)'), ('B', 'Group B (≤1Cr)')], default='B', help_text='Group A for investments >1Cr, Group B for ≤1Cr (auto-assigned based on investment_capacity)', max_length=1),
        ),
        migrations.CreateModel(
            name='SecureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID token for secure access', unique=True)),
                ('expires_at', models.DateTimeField(help_text='Expiry date and time for this secure link')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time this link was accessed', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this link has been accessed')),
                ('created_by', models.ForeignKey(help_text='User who created this secure link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secure_links', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(help_text='Investor this secure link is for', on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Secure Link',
                'verbose_name_plural': 'Secure Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='investors_s_token_dd2d4e_idx'), models.Index(fields=['expires_at', 'is_active'], name='investors_s_expires_f412d5_idx')],
            },
        ),
    ]
