# Generated by Django 5.1.1 on 2025-12-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_remove_deal_approval_workflow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('kyc', 'KYC Document'), ('bank', 'Bank Statement'), ('pitch_deck', 'Pitch Deck'), ('financials', 'Financials'), ('deal_doc', 'Deal Document'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
