# Generated by Django 5.1.1 on 2025-12-22 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('investors', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='allotted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='is_allotted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commitment',
            name='meeting_requested',
            field=models.BooleanField(default=False, help_text='Investor requested meeting with promoters'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='questions',
            field=models.TextField(blank=True, help_text='Questions from investor'),
        ),
        migrations.AddField(
            model_name='deal',
            name='expected_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='max_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='min_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investor',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='investor',
            name='dp_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='DP ID'),
        ),
        migrations.AddField(
            model_name='investor',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Active after Partner confirmation'),
        ),
        migrations.AddField(
            model_name='investor',
            name='profession',
            field=models.CharField(blank=True, help_text='Profession/Nature of Income', max_length=100),
        ),
        migrations.AddField(
            model_name='securelink',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='securelink',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('kyc', 'KYC Document'), ('bank', 'Bank Statement'), ('pitch_deck', 'Pitch Deck'), ('financials', 'Financials')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('changes', models.JSONField(help_text='JSON storage of changed fields', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
