# Generated by Django 5.1.1 on 2025-12-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_commitment_allotted_amount_commitment_is_allotted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Internal notes'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested - Review Needed'), ('approved', 'Approved - Payment Requested'), ('payment_uploaded', 'Payment Proof Uploaded'), ('confirmed', 'Final Confirmed'), ('rejected', 'Rejected')], default='interested', max_length=20),
        ),
    ]
