# Generated by Django 5.1.1 on 2025-12-23 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_commitment_admin_comment_alter_commitment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The Admin or Partner who created this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='The Gmail address used to send invites.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='The 16-character App Password generated from Google Account Security.', max_length=255, null=True),
        ),
    ]
