# Generated by Django 5.1.1 on 2025-12-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_user_created_by_user_smtp_email_user_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='securelink',
            name='commitment',
            field=models.ForeignKey(blank=True, help_text='The specific commitment this link allows payment for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_links', to='investors.commitment'),
        ),
    ]
