# Generated by Django 6.0 on 2026-01-03 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0007_securelink_commitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='mobile',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{9,15}$')]),
        ),
    ]
