# Generated by Django 5.2.4 on 2026-01-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0009_alter_investor_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('pre_ipo', 'Pre-IPO'), ('ipo_anchor', 'IPO - Anchor'), ('private_round', 'Private Round'), ('fundraising', 'Fundraising'), ('others', 'Others')], default='others', help_text='Categorization of the deal (e.g., Pre-IPO, Anchor)', max_length=50),
        ),
        migrations.AddField(
            model_name='deal',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to the team (not investors).'),
        ),
        migrations.AddField(
            model_name='deal',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to Corporate Video (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('closing_soon', 'Closing Soon'), ('filled', 'Filled'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('kyc', 'KYC Document'), ('bank', 'Bank Statement'), ('pitch_deck', 'Pitch Deck'), ('financials', 'Financials'), ('write_up', 'Write Up'), ('one_pager', 'One Pager'), ('term_sheet', 'Term Sheet'), ('projections', 'Projections')], default='other', max_length=20),
        ),
    ]
