# Generated by Django 5.2.4 on 2026-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0010_deal_category_deal_internal_notes_deal_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='preferred_duration',
            field=models.CharField(blank=True, choices=[('short', 'Short Term (< 1 Year)'), ('medium', 'Medium Term (1-3 Years)'), ('long', 'Long Term (> 3 Years)')], max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Name of the person or entity who referred this investor', max_length=255),
        ),
        migrations.AddField(
            model_name='investor',
            name='remark',
            field=models.TextField(blank=True, help_text='Internal remarks or notes about this investor'),
        ),
        migrations.AddField(
            model_name='investor',
            name='risk_appetite',
            field=models.CharField(blank=True, choices=[('low', 'Low - Conservative'), ('medium', 'Medium - Balanced'), ('high', 'High - Aggressive')], max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='ticket_size_preference',
            field=models.CharField(blank=True, choices=[('5L-10L', '5L - 10L'), ('10L-25L', '10L - 25L'), ('25L-50L', '25L - 50L'), ('50L+', 'Above 50L')], max_length=20),
        ),
    ]
