# Generated by Django 5.1.1 on 2026-01-06 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0011_investor_preferred_duration_investor_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='approvals',
            field=models.ManyToManyField(blank=True, help_text='Partners/Admins who have approved this deal.', related_name='approved_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
