# Generated by Django 5.2.4 on 2026-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investors", "0011_investor_preferred_duration_investor_referred_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="aadhaar",
            field=models.CharField(
                blank=True,
                help_text="Aadhaar Number (will be masked in display)",
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="investor",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[("A", "Group A (>1Cr)"), ("B", "Group B (≤1Cr)")],
                default="B",
                help_text="Group A for investments >1Cr, Group B for ≤1Cr (auto-assigned based on investment_capacity)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="pan",
            field=models.CharField(
                blank=True, help_text="PAN Card Number", max_length=10, unique=True
            ),
        ),
    ]
