# Generated by Django 5.2.4 on 2026-01-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investors", "0012_alter_investor_aadhaar_alter_investor_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="dob",
            field=models.DateField(blank=True, verbose_name="Date of Birth"),
        ),
    ]
