# Generated by Django 5.1.1 on 2026-01-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0012_deal_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='aadhaar',
            field=models.CharField(blank=True, help_text='Aadhaar Number (will be masked in display)', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='dp_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DP ID'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'Group A (>1Cr)'), ('B', 'Group B (≤1Cr)')], default='B', help_text='Group A for investments >1Cr, Group B for ≤1Cr (auto-assigned based on investment_capacity)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='pan',
            field=models.CharField(blank=True, help_text='PAN Card Number', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='preferred_duration',
            field=models.CharField(blank=True, choices=[('short', 'Short Term (< 1 Year)'), ('medium', 'Medium Term (1-3 Years)'), ('long', 'Long Term (> 3 Years)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='profession',
            field=models.CharField(blank=True, help_text='Profession/Nature of Income', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Name of the person or entity who referred this investor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='remark',
            field=models.TextField(blank=True, help_text='Internal remarks or notes about this investor', null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='risk_appetite',
            field=models.CharField(blank=True, choices=[('low', 'Low - Conservative'), ('medium', 'Medium - Balanced'), ('high', 'High - Aggressive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='ticket_size_preference',
            field=models.CharField(blank=True, choices=[('5L-10L', '5L - 10L'), ('10L-25L', '10L - 25L'), ('25L-50L', '25L - 50L'), ('50L+', 'Above 50L')], max_length=20, null=True),
        ),
    ]
