# Generated by Django 6.0 on 2026-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0014_alter_investor_aadhaar_alter_investor_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='preferred_industries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
