# Generated by Django 6.0 on 2026-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0015_investor_preferred_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_industries',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('consumer_goods', 'Consumer Goods'), ('energy', 'Energy'), ('others', 'Others')], max_length=100, null=True),
        ),
    ]
