# Generated by Django 6.0 on 2026-01-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0016_alter_investor_preferred_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_industries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
