# Generated by Django 6.0 on 2026-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0017_alter_investor_preferred_industries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='investor',
            name='preferred_industries',
        ),
        migrations.AddField(
            model_name='investor',
            name='preferred_industries',
            field=models.ManyToManyField(blank=True, null=True, to='investors.industry'),
        ),
    ]
