# Generated by Django 6.0 on 2026-01-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0018_industry_remove_investor_preferred_industries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_industries',
            field=models.ManyToManyField(blank=True, to='investors.industry'),
        ),
    ]
