# Generated by Django 6.0 on 2026-01-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0019_alter_investor_preferred_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_industries',
            field=models.ManyToManyField(blank=True, related_name='investors', to='investors.industry'),
        ),
    ]
