# Generated by Django 6.0 on 2026-01-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0020_alter_investor_preferred_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_industries',
            field=models.ManyToManyField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('consumer_goods', 'Consumer Goods'), ('energy', 'Energy'), ('others', 'Others')], related_name='investors', to='investors.industry'),
        ),
    ]
