# Generated by Django 6.0 on 2026-01-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0021_alter_investor_preferred_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_industries',
            field=models.ManyToManyField(blank=True, to='investors.industry'),
        ),
    ]
