# Generated by Django 6.0 on 2026-01-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0022_alter_investor_preferred_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='preferred_industries',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AddField(
            model_name='investor',
            name='preferred_industries',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred industries', null=True),
        ),
    ]
