# Generated by Django 6.0 on 2026-01-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0023_remove_investor_preferred_industries_delete_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='risk_appetite',
            field=models.CharField(blank=True, choices=[('low', 'Low - Conservative'), ('medium', 'Medium - Balanced'), ('high', 'High - Aggressive'), ('fixed', 'Fixed')], max_length=20, null=True),
        ),
    ]
