# Generated by Django 6.0 on 2026-01-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0024_alter_investor_risk_appetite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_duration',
            field=models.CharField(blank=True, choices=[('short', 'Short Term (< 1 Year)'), ('medium', 'Medium Term (1-3 Years)'), ('long', 'Long Term (> 3 Years)'), ('any', 'Any')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='risk_appetite',
            field=models.CharField(blank=True, choices=[('low', 'Conservative - Low Return '), ('medium', 'Balanced - Medium Return'), ('high', 'Aggressive - High Return'), ('fixed', 'Fix Return')], max_length=20, null=True),
        ),
    ]
