# Generated by Django 6.0 on 2026-01-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0025_alter_investor_preferred_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='payment_timeline',
            field=models.CharField(blank=True, help_text='Duration to fulfill the amount', max_length=100, null=True),
        ),
    ]
