# Generated by Django 6.0 on 2026-01-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0026_commitment_payment_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='preferred_industries',
            field=models.JSONField(blank=True, help_text='List of preferred industries', null=True),
        ),
    ]
