# Generated by Django 6.0 on 2026-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0027_alter_investor_preferred_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='payment_timeline_type',
            field=models.CharField(blank=True, choices=[('years', 'Years'), ('months', 'Months'), ('days', 'Days')], help_text='Type of payment timeline', max_length=20, null=True),
        ),
    ]
