# Generated by Django 6.0 on 2026-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0028_commitment_payment_timeline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Approved amount in INR', max_digits=15),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Committed/Interested amount in INR', max_digits=15),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='payment_timeline_type',
            field=models.CharField(blank=True, choices=[('years', 'Years'), ('months', 'Months'), ('weeks', 'Weeks'), ('days', 'Days')], default='draft', max_length=20, null=True),
        ),
    ]
