# Generated by Django 6.0 on 2026-01-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0029_commitment_approved_amount_alter_commitment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='payment_timeline_type',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('weeks', 'Weeks'), ('months', 'Months'), ('days', 'days')], default='draft', max_length=20, null=True),
        ),
    ]
