# Generated by Django 6.0 on 2026-01-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0031_texttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier like: welcome_email, reset_password', max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use Django template syntax: {{ user.name }}, {{ otp }}')),
                ('is_html', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TextTemplate',
        ),
    ]
