# Generated by Django 6.0 on 2026-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0032_emailtemplate_delete_texttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
