# Generated by Django 6.0 on 2026-01-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0034_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextContent',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='title',
            field=models.CharField(default='new title', max_length=200),
        ),
    ]
