# Generated by Django 6.0 on 2026-01-23 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0035_delete_textcontent_mymodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='approvals',
            field=models.ManyToManyField(blank=True, help_text='Partners/Admins who have approved this deal.', related_name='approved_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
