# Generated by Django 6.0 on 2026-01-23 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0036_deal_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='assigned_team_member',
        ),
        migrations.AddField(
            model_name='investor',
            name='assigned_team_members',
            field=models.ManyToManyField(blank=True, help_text='Team members assigned to manage this investor', limit_choices_to={'role': 'team_member'}, related_name='assigned_investors', to=settings.AUTH_USER_MODEL),
        ),
    ]
