# Generated by Django 6.0 on 2026-01-24 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0037_remove_investor_assigned_team_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='assigned_team_members',
            field=models.ManyToManyField(blank=True, help_text='Team members assigned to manage this deal', limit_choices_to={'role': 'team_member'}, related_name='assigned_deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
