# Generated by Django 6.0 on 2026-01-27 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0038_deal_assigned_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='internal_notes',
        ),
        migrations.CreateModel(
            name='DealInternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(help_text='Internal remark or note content')),
                ('status', models.CharField(blank=True, help_text='Status related to this note (optional)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes_list', to='investors.deal')),
                ('user', models.ForeignKey(help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal Internal Note',
                'verbose_name_plural': 'Deal Internal Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
