# Generated by Django 6.0 on 2026-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0039_remove_deal_internal_notes_dealinternalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealinternalnote',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved')], help_text='Update the workflow status of the deal (optional)', max_length=20, null=True),
        ),
    ]
