# Generated by Django 6.0 on 2026-01-31 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0040_alter_dealinternalnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investor',
            name='ticket_size_preference',
            field=models.CharField(blank=True, choices=[('Less_25L', 'Less then 25L'), ('25L_1CR', '25L - 1CR'), ('1CR_3CR', '1CR - 3CR'), ('3CR', 'Above 3CR')], max_length=20, null=True),
        ),
    ]
