# Generated by Django 6.0 on 2026-02-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0041_investor_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='created_by',
        ),
    ]
