# Generated by Django 6.0 on 2026-02-01 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0042_remove_investor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investors', to=settings.AUTH_USER_MODEL),
        ),
    ]
