# Generated by Django 6.0 on 2026-02-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0043_investor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='not_interested_remark',
            field=models.TextField(blank=True, help_text='Reason for not interested', null=True),
        ),
    ]
