# Generated by Django 6.0 on 2026-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0044_commitment_not_interested_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('pending', 'Invitation Sent / Response Awaited'), ('not_committed', 'Not Committed'), ('committed', 'Committed'), ('approved', 'Approved - Payment Requested'), ('payment_uploaded', 'Payment Proof Uploaded'), ('confirmed', 'Final Confirmed'), ('rejected', 'Rejected')], default='interested', max_length=20),
        ),
    ]
