# Generated by Django 6.0 on 2026-02-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0045_alter_commitment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='not_interested_remark',
            field=models.TextField(default='', help_text='Reason for not interested'),
        ),
    ]
