# Generated by Django 6.0 on 2026-02-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0046_alter_commitment_not_interested_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[('pending', 'Invitation Sent / Response Awaited'), ('not_committed', 'Not Committed'), ('committed', 'Committed'), ('approved', 'Approved - Payment Requested'), ('payment_uploaded', 'Payment Proof Uploaded'), ('confirmed', 'Investment Confirmed'), ('rejected', 'Rejected')], default='interested', max_length=20),
        ),
        migrations.AlterField(
            model_name='investor',
            name='group',
            field=models.CharField(blank=True, choices=[('Less_25L', 'Less_25L'), ('25L', '25L'), ('50L', '50L'), ('75L', '75L'), ('1CR', '1CR'), ('1.5CR', '1.5CR'), ('2CR', '2CR'), ('2.5CR', '2.5CR'), ('3CR', '3CR'), ('3.5CR', '3.5CR'), ('4CR', '4CR'), ('4.5CR', '4.5CR'), ('5CR', '5CR'), ('Above_5CR', 'Above_5CR')], default='C', help_text='Group A for investments >1Cr, Group B for ≤1Cr (auto-assigned based on investment_capacity)', max_length=10, null=True),
        ),
    ]
