# Generated by Django 6.0 on 2026-02-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0047_alter_commitment_status_alter_investor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='not_interested_remark',
            field=models.TextField(blank=True, default='', help_text='Reason for not interested', null=True),
        ),
    ]
